### ISSUE TITLE
Install link no longer working (points to broken link) 

### ISSUE THREAD

**Issue by thadguidry** [cayleygraph/website#3]
See https://github.com/cayleygraph/website/blob/226fcc14a669f64f97a32004037e693802cfb22e/config.toml#L38

I did see references to that old MD doc link in these files:
https://github.com/cayleygraph/cayley/search?q=Quickstart-As-Application&type=Code

Perhaps it should just point to the README.md file instead where it would have an Installation docs link?  This would coincide with the ask on https://github.com/cayleygraph/cayley/issues/825

**Comment by iddan** [comment]
Thank you for reporting! Should be solved by https://github.com/cayleygraph/website/commit/93a3510ff602d33fd968a6398d4019a7dda7f003

**Comment by iddan** [comment]
Until it will be deployed I recreated the file in the docs folder: https://github.com/cayleygraph/cayley/commit/f476836a47cf10a46936c4246545bd599622ca46
